name: Weekly Jira Report

on:
  schedule:
    - cron: '0 7 * * 5'
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests boto3 jinja2

      - name: Generate Credentials File
        env:
          USER_DATA_JSON: ${{ secrets.USER_DATA_JSON }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          TEAMS_WORKFLOW_URL: ${{ secrets.TEAMS_WORKFLOW_URL }}
        run: python generate_config.py

      - name: Run Jira Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
        run: python jira_report.py
